#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "XK so"
id = "f997b721aeae42afbc286f25a4326732"

[[d1_databases]]
binding = "d1"
database_name = "smail"
database_id = "dc3e453e-8d22-4956-ab05-6285ef0c6c1b"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"
